use_frameworks!

platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MCBaseUtils_Example' do
  pod 'MCBaseUtils', :path => '../'

  target 'MCBaseUtils_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
